Repository fga-eps-mds/2019.2-Questmark, pull requests merged in 2019-09, with the labels that each got.

#30 Configurações docker.
  .gitignore
  Dockerfile
  docker-compose.yml
  index.js
  package.json
Labels: MDS, backend

#33 [#27]Criar template de pull request e revisar templates já existentes
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, github

#34 Criação api básica
  index.js
  routes/forms.js
  routes/users.js
Labels: backend

#43 [#36] configurar api com banco
  index.js
  models/Forms.js
  models/Users.js
  package.json
  routes/forms.js
  routes/users.js
Labels: backend

#45 [#37]Adição do WMD
  docs/Protótipo de baixa fidelidade/Protótipo.pdf
  docs/documento-de-visao.md
  docs/gestao-de-configuracao-de-software.md
  docs/uc_questmark.png
  wmdQuestmark/Makefile
  wmdQuestmark/jsmin.py
  wmdQuestmark/markdownhelp.html
  wmdQuestmark/showdown.js
  wmdQuestmark/wmd-buttons.png
  wmdQuestmark/wmd-buttons.psd
  wmdQuestmark/wmd-test.html
  wmdQuestmark/wmd.combined.js
  wmdQuestmark/wmd.combined.min.js
  wmdQuestmark/wmd.css
  wmdQuestmark/wmd.js
Labels: enhancement
